success check in ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -31,6 +31,9 @@ jobs:
         if grep -E "Exception|RuntimeError" server-output.log; then 
           echo "Success message not found. Check server-output.log for details."
           exit 1
+        elif ! grep -q "entering server-mode" ballistica-output.log; then
+          echo "Success message not found in ballistica's output."
+          exit 1
         fi
     - name: Upload ballistica output as artifact
       if: always()  
